### ISSUE TITLE
Not a issue. It's an answer

### ISSUE THREAD

**Issue by Cusiri1971** [rduivenvoorde/xytools#7]
You plugin is GREAT, yes in uppercase.
Thanks a lot.
I have a question, please.
¿why don't include to save attribute table to libreoffice calc file?
I don't know py programming, then i don't know how it's work and the most important thing i don't understand the difficulties.
So is just a question.
Thanks a lot and congratulation for your excelent plugin

**Comment by rduivenvoorde** [comment]
@Cusiri1971 thanks for the thanks  :-)

To be honest I did not have a look at the plugin for a long time... but the main reason was that I did not have time at that time (and saving it to excel was ... well just enough, you could then open it in LibreOffice if you want...).
And nowadays, time is valuable :-) But... have a look into some Python coding resources, it is really fun! And if you do a working pull request, I'm happy to pull it in.

Regards,

Richard
